### PR TITLE
Result verification3

### PR DESCRIPTION
**Pull request by Raghu-Srungavarapu**
Please review and let me know if you need any changes.

### CODE REVIEW

**Comment by Raghu-Srungavarapu** [comment]
@sfsinger19103 

Instructions to run this verification module. It is interactive. 
1) Runelection_anomaly\src\election_anomaly\verify_result.
2) Select result file 1 for comparison.
3) Select result file 2 for comparison.

**Comment by sfsinger19103** [comment]
Doesn't run on files that don't distinguish CountItemType (output of `Analyer.top_counts()`):

```
Connected to pydev debugger (build 193.7288.30)
Select result file 1 for comparision
Enter path to file (or hit return to use pop-up window to find it).
/Users/singer3/Documents/rollups/2018 General/Pennsylvania;Philadelphia/by_ward/TYPEall_STATUSunknown.txt
Select result file 2 for comparision
Enter path to file (or hit return to use pop-up window to find it).
/Users/singer3/Documents/rollups/2018 General/Pennsylvania;Philadelphia/by_ward/TYPEall_STATUSunknown.txt
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/singer3/PycharmProjects/results_analysis/src/election_anomaly/verify_results/result_verification.py", line 48, in <module>
    differences_df =  differences_df.set_index(['contest_type', 'Contest', 'contest_district_type', 'Selection','ReportingUnit', 'CountItemType', '_merge'])
  File "/Users/singer3/PycharmProjects/results_analysis/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 4300, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['CountItemType'] are in the columns"
```

**Comment by sfsinger19103** [comment]
Program indicated that a file did not match itself.

```
Select result file 1 for comparision
Enter path to file (or hit return to use pop-up window to find it).
/Users/singer3/Documents/rollups/2018 General/Pennsylvania;Philadelphia/by_ward/TYPEmixed_STATUSunknown.txt
Select result file 2 for comparision
Enter path to file (or hit return to use pop-up window to find it).
/Users/singer3/Documents/rollups/2018 General/Pennsylvania;Philadelphia/by_ward/TYPEmixed_STATUSunknown.txt
Vote counts do not match in 3951 rows
Do you want to look at these rows  (y/n)?
```

**Comment by sfsinger19103** [comment]
Documentation should tell user how to interpret output file. I wasn't sure what this meant:

```

  |   |   |   |   |   | Count
-- | -- | -- | -- | -- | -- | --
_merge |   |   |   |   |   | both
contest_type | Contest | contest_district_type | Selection | ReportingUnit | CountItemType |  
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 1 | absentee | 41
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 1 | election-day | 1187
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 1 | provisional | 6
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 10 | absentee | 31
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 10 | election-day | 1453
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 10 | provisional | 23
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 11 | absentee | 8
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 11 | election-day | 480
BallotMeasure | CITY BOND QUESTION (Bill No. 180552) | county | No | Pennsylvania;Philadelphia;Ward 11 | provisional | 7
```

**Comment by sfsinger19103** [comment]
If user runs program twice, output file second time unfortunately overwrites the output file from the first run. One way to avoid overwriting is to append a number if the file already exists. Another way is to append a time stamp. @ericmtsai may have a more elegant suggestion.

**Comment by sfsinger19103** [comment]
spelling: "default", not "deafault"

**Comment by sfsinger19103** [comment]
entering non-existent output folder yielded neither output nor an error message.

**Comment by sfsinger19103** [comment]
Please work with @ericmtsai to design a more elegant interface.

**Comment by Raghu-Srungavarapu** [comment]
Addressed these changes in another pull request. 
https://github.com/sfsinger19103/election_anomaly/pull/119

**Pull request closed without merging**
