### PR TITLE
Munge pa primary 3

### PR DESCRIPTION
**Pull request by sfsinger19103**
Major changes:
 - change in data model (CandidateSelection includes Party_Id; Candidate does not)
 - corresponding change to ALL jurisdiction directories: Candidate.txt no longer has Party column
 - new module `preparation` with routines to help prepare jurisdiction files
 - incorporates `bug-fix` branch, obviating #111

### CODE REVIEW

**Comment by ericmtsai** [comment]
@sfsinger19103 I ran into 3 issues when trying this branch on PA data:
1. Seems like `run_time.par` got removed from the .gitignore and is part of the repo now.
2. When I run `dataloader=DataLoader()`, I get this message:
```
{'format.txt': {'format_problems': 'Wrong number of rows in format.txt. \nFirst column must be exactly:\nheader_row_count\nfield_name_row\nfield_names_if_no_field_name_row\ncount_columns\nfile_type\nencoding\nthousands_separator'}}
```
3. When I ran `dataloader.load_results()`, I got this (possibly due to the previous error):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eric/Desktop/election_anomaly/src/election_anomaly/__init__.py", line 136, in load_results
    results_info=results_info,aux_data_dir=self.d['aux_data_dir'])
  File "/Users/eric/Desktop/election_anomaly/src/election_anomaly/user_interface/__init__.py", line 642, in new_datafile
    raw, err = read_combine_results(munger, raw_path, project_root,err,aux_data_dir=aux_data_dir)
  File "/Users/eric/Desktop/election_anomaly/src/election_anomaly/user_interface/__init__.py", line 614, in read_combine_results
    working = mr.cast_cols_as_int(working, mu.count_columns,mode='index')
AttributeError: 'NoneType' object has no attribute 'count_columns'
```

**Comment by sfsinger19103** [comment]
There was a line missing from the munger `format.txt` file. I've corrected them all now. Try again?

(new line in format.txt is `field_names_if_no_field_name_row	None`, added when code was revised to allow files without header rows)

**Comment by ericmtsai** [comment]
This is working now for both 2018 General and 2020 Primary. However, for both elections, I get a munger error when I run the check_errors() function:
```
{'munger_internal_consistency': 'At least one source in cdf_elements.txt is not recognized: other '}
```
I think since we tell users in the README that these should all return None, this should be addressed even though it doesn't affect the data loading itself.

**Comment by sfsinger19103** [comment]
Eric, I'm not getting that error on `ca07675cacddbaa8959758ea738cd58c3849e4f5`. Pls send me a revision number and a copy of your` run_time.par` and `cdf_elements.txt` from your munger.

**Comment by sfsinger19103** [comment]
I stand corrected: I am getting that error. Will fix, test and resubmit.

**Comment by sfsinger19103** [comment]
fixed and tested.

**Comment by ericmtsai** [comment]
Working! Also it's the first time I've loaded multiple elections into the same DB and it seems to work great.

**Pull request merged**
