### PR TITLE
cleanup-pick-munger

### PR DESCRIPTION
**Pull request by ericmtsai**
This PR cleans up the interactivity in the ui.pick_munger() function. This assumes the munger directory is identified in the run_time.par file, and if this directory is not found, it automatically creates the directory and files and returns a message to the user through the `error` dictionary. If the munger directory is found, it checks that the files are complete and consistent with each other, returning any problems that it finds.

If this code is successful (assuming everything up through the `track_results_file` code is run correctly), it should go directly to the `new_datafile` section, asking the user: `Pick the _datafile record from the database:`.

### CODE REVIEW

**Comment by sfsinger19103** [comment]
Running the program on a brand new jurisdiction (without creating jurisdiction folder myself first), got failure due to missing `remark.txt`:
```cps-urbn650c-pk:Data_Loading singer3$ python3 /Users/singer3/PycharmProjects/results_analysis/src/election_anomaly/main_routines/050_load_datafile.py
WARNING: if necessary files are missing from the directory CA,
system may fail.
No subdirectory CA in /Users/singer3/PycharmProjects/results_analysis/src/jurisdictions. Here are the existing subdirectories:
   directory
0         MI
1      Phila
2         CO
3         FL
4  README.md
5         PA
6         NC
7         MD
Enter the number of the desired directory (or nothing, if your choice is not on the list):

Enter subdirectory name (alphanumeric and underscore only)
CA
Confirm creation of directory (y/n)?
/Users/singer3/PycharmProjects/results_analysis/src/jurisdictions/CA
y
Traceback (most recent call last):
  File "/Users/singer3/PycharmProjects/results_analysis/src/election_anomaly/main_routines/050_load_datafile.py", line 13, in <module>
    juris = ui.pick_juris_from_filesystem(d['project_root'],juris_name=d['juris_name'])
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/user_interface/__init__.py", line 302, in pick_juris_from_filesystem
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/juris_and_munger/__init__.py", line 93, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/Users/singer3/PycharmProjects/results_analysis/src/jurisdictions/CA/remark.txt'
cps-urbn650c-pk:Data_Loading singer3$ 
```

**Comment by sfsinger19103** [comment]
Ugly fail due to mistake in database parameter file (used `database` instead of `dbname`:
```[postgresql]
host=pgsql12.rc.pdx.edu
port=5432
database=election_data_science
...
```
Error message: 
```
Traceback (most recent call last):
  File "/Users/singer3/PycharmProjects/results_analysis/src/election_anomaly/main_routines/050_load_datafile.py", line 16, in <module>
    error = dbr.establish_connection(paramfile=d['db_paramfile'],db_name=d['db_name'])
  File "/usr/local/lib/python3.7/site-packages/election_anomaly-0.1-py3.7.egg/election_anomaly/db_routines/__init__.py", line 85, in establish_connection
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/extensions.py", line 160, in make_dsn
    "you can't specify both 'database' and 'dbname' arguments")
TypeError: you can't specify both 'database' and 'dbname' arguments
```

**Comment by sfsinger19103** [comment]
In `010_check_jurisdiction.py `, `dictionary.txt` would be better checked last, not first, matching the order the user will probably use to create files.
```
cps-urbn650c-pk:Data_Loading singer3$ python3 /Users/singer3/PycharmProjects/results_analysis/src/election_anomaly/main_routines/010_check_jurisdiction.py 
Directory /Users/singer3/PycharmProjects/results_analysis/src/jurisdictions/CA already exists, will be preserved

Checking dictionary.txt
File dictionary.txt has just been created.
Enter information in the file, then hit return to continue.
```

**Comment by sfsinger19103** [comment]
Ugly fail on encoding error in Candidate.txt file; should fail gracefully and allow user to enter encoding; also we should assume iso-8859-1 (which, unlike utf-8, can handle Spanish characters).

```
Checking Candidate.txt
File Candidate.txt has just been created.
Enter information in the file, then hit return to continue.
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1130, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1254, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1269, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1459, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 13: invalid start byte
```

**Comment by sfsinger19103** [comment]
It's good that ReportingUnitType is showing now (when user needs to pick a ReportingUnit); however user should not see the ReportingUnitTypeId and the OtherReportingUnitType string.
```
Specify the ReportingUnit for this _datafile
Pick the ReportingUnit record from the database:
                                  Name  ReportingUnitType_Id  \
0                           California                    19   
1            California;Alameda County                     9   
2             California;Alpine County                     9   
3             California;Amador County                     9   
```

**Comment by sfsinger19103** [comment]
Ugly fail in 050 if munger hasn't been set up yet,:
```
	# pick munger
	munger, error = ui.pick_munger(
		project_root=d['project_root'],
		mungers_dir=os.path.join(d['project_root'],'mungers'),session=sess,munger_name=d['munger_name'])

	# load new datafile
	ui.new_datafile(sess,munger,d['results_file'],juris=juris,project_root=d['project_root'])
```
failure happens in `read_datafile()` because munger is None

**Comment by ericmtsai** [comment]
@sfsinger19103 It seems like none of these issues are related to the work done on this PR though? This deals specifically with the flow through ui.pick_munger().

**Pull request merged**
